Added perfect forward secrecy and extensive testing
Changed the protocol to use ephemeral-ephemeral Diffie-Hellman
key exchange instead of ephemeral-static DH. "certs/peer.sig"
and "private/derive.pem", if generated by version 2.0
"gen-cable-username", are not used anymore.

Added "simulate", an extensive testing script. It should be run
after "make clean" , since it passes -DTESTING to C compiler for
reduced timeouts and logging to terminal. A mockup "curl" script
is used for simulating client-server communication.

Moved hex2base32 to libexec directory. Except for "cable-info",
bundled programs do not rely on PATH setting anymore.

"cabled" init service wrapper now unconditionally removes
old "queue/tmp.*" and "rqueue/*.new" directories.

Fixed a "recv.mac" reading bug that prevented message arrival
verification when source and destination are different.

FCGI service now provisionally returns the version identifier
for all correct requests, same as "/request/ver" response.

diff --git a/cable/fetch b/cable/fetch
--- a/cable/fetch
+++ b/cable/fetch
@@ -41,16 +41,41 @@ check_userhost() {
 }
 
 
+# Retry curl request for 400+ status codes
+retrycurl() {
+    local status= delay=
+
+    for delay in 0 5 10 15; do
+        sleep ${delay}
+        status=0; curl "$@" || status=$?
+
+        if [ ${status} != 22 ]; then
+            break
+        fi
+    done
+
+    return ${status}
+}
+
+
 case "${cmd}" in
 send)
     # <send> [fetch loop]
     if [ -e ${queue}/"${msgid}"/${cmd}.req ]; then
         prefix=`urlprefix ${queue}`
 
+        susername=`cat ${queue}/"${msgid}"/susername | tr -cd '[:alnum:].-' | tr '[:upper:]' '[:lower:]'`
+        shostname=`cat ${queue}/"${msgid}"/shostname | tr -cd '[:alnum:].-' | tr '[:upper:]' '[:lower:]'`
+        check_userhost "${susername}" "${shostname}"
+
+        curl -sSfg "${prefix}"/request/msg/"${msgid}"/"${shostname}"/"${susername}"
+
+        # TODO: with precomputed rpeers, a delay will be much less likely
+        retrycurl -sSfg -o ${queue}/"${msgid}"/rpeer.sig "${prefix}"/rqueue/"${msgid}".key
+
         # A multi-URI curl command doesn't fail on a bad early fetch
         curl -sSfg -o ${queue}/"${msgid}"/ca.pem     "${prefix}"/certs/ca.pem
         curl -sSfg -o ${queue}/"${msgid}"/verify.pem "${prefix}"/certs/verify.pem
-        curl -sSfg -o ${queue}/"${msgid}"/peer.sig   "${prefix}"/certs/peer.sig
 
         mv ${queue}/"${msgid}"/${cmd}.req ${queue}/"${msgid}"/${cmd}.rdy
     else
@@ -60,18 +85,19 @@ send)
 
 recv)
     # <recv> [fetch loop]
-    if [ -e ${rqueue}/"${msgid}"/${cmd}.req ]; then
+    if [ -e ${rqueue}/"${msgid}"/${cmd}.req  -a  -e ${rqueue}/"${msgid}"/send.mac  -a \
+         ! -e ${rqueue}/"${msgid}"/${cmd}.rdy  -a  ! -e ${rqueue}/"${msgid}"/${cmd}.ok ]; then
         prefix=`urlprefix ${rqueue}`
 
         # A multi-URI curl command deosn't fail on a bad early fetch
         curl -sSfg -o ${rqueue}/"${msgid}"/message.enc "${prefix}"/queue/"${msgid}"
-        curl -sSfg -o ${rqueue}/"${msgid}"/peereph.sig "${prefix}"/queue/"${msgid}".key
+        curl -sSfg -o ${rqueue}/"${msgid}"/speer.sig   "${prefix}"/queue/"${msgid}".key
         curl -sSfg -o ${rqueue}/"${msgid}"/ca.pem      "${prefix}"/certs/ca.pem
         curl -sSfg -o ${rqueue}/"${msgid}"/verify.pem  "${prefix}"/certs/verify.pem
 
         mv ${rqueue}/"${msgid}"/${cmd}.req ${rqueue}/"${msgid}"/${cmd}.rdy
     else
-        error "${cmd}.req not found"
+        error "${cmd}.req (without .rdy/.ok) or send.mac not found"
     fi
     ;;
 
diff --git a/cable/loop b/cable/loop
--- a/cable/loop
+++ b/cable/loop
@@ -40,11 +40,12 @@ error() {
 
 # Sanity checks
 [ ${#msgid} = 40 ] || error "bad msgid"
-[ -r "${msgdir}" ] || error "bad permissions"
+[ -r "${msgdir}" ] || error "cannot access"
 
 
 # .del actions: blocking lock (to let the renaming action finish)
 if [ "${dirid}" != "${msgid}" ]; then
+
     if [ ${qtype} = queue ]; then
 
         if [ -e "${msgdir}" ]; then
@@ -62,7 +63,9 @@ if [ "${dirid}" != "${msgid}" ]; then
         fi
 
     fi
+
 else
+
     if [ ${qtype} = queue ]; then
 
         # non-blocking lock of combined operations
@@ -73,6 +76,7 @@ else
         "${validate}" ${qtype} "${msgid}"
         set +e
 
+        # handle ack first, to retry send if failed
         if   [ -e "${msgdir}"/ack.ok  ]; then
             "${comm}"   ack  "${msgid}"
         elif [ -e "${msgdir}"/ack.req ]; then
@@ -108,18 +112,28 @@ else
         "${validate}" ${qtype} "${msgid}"
         set +e
 
-        if   [ -e "${msgdir}"/recv.req ]; then
-                 "${fetch}"  recv "${msgid}" && \
-                 "${crypto}" recv "${msgid}" && \
-            exec "${comm}"   recv "${msgid}"
-        elif [ -e "${msgdir}"/recv.rdy ]; then
-                 "${crypto}" recv "${msgid}" && \
-            exec "${comm}"   recv "${msgid}"
+        if   [ -e "${msgdir}"/recv.rdy ]; then
+            "${crypto}" recv "${msgid}" && \
+            "${comm}"   recv "${msgid}"
         elif [ -e "${msgdir}"/recv.ok  ]; then
-            exec "${comm}"   recv "${msgid}"
+            "${comm}"   recv "${msgid}"
+        elif [ -e "${msgdir}"/recv.req ]; then
+            "${fetch}"  recv "${msgid}" && \
+            "${crypto}" recv "${msgid}" && \
+            "${comm}"   recv "${msgid}"
+        fi
+
+        if [ -e "${msgdir}"/peer.req ]; then
+                 "${crypto}" peer "${msgid}" && \
+            exec "${comm}"   peer "${msgid}"
+        elif [ -e "${msgdir}"/peer.ok  ]; then
+            if [ ! -e "${msgdir}"/recv.ok  ]; then
+                exec "${comm}" peer "${msgid}"
+            fi
         else
-            error "recv.req/rdy/ok not found"
+            error "peer.req/ok not found"
         fi
 
     fi
+
 fi
